// Generated by https://quicktype.io

export interface User {
  name: string;
  id: string;
  email: string;
}

export interface AccountResponse {
  name: string;
  email: string;
  picture: Picture;
  accounts: Accounts;
  id: string;
  accessToken: string;
}

export interface Accounts {
  data: PageData[];
  paging: Paging;
}

export interface PageData {
  access_token: string;
  category: string;
  category_list: CategoryList[];
  name: string;
  id: string;
  tasks: string[];
}

export interface CategoryList {
  id: string;
  name: string;
}

export interface Paging {
  cursors: Cursors;
}

export interface Cursors {
  before: string;
  after: string;
}

export interface Picture {
  data: PictureData;
}

export interface PictureData {
  height: number;
  is_silhouette: boolean;
  url: string;
  width: number;
}
